### ISSUE TITLE
Placed Object glitches around

### ISSUE THREAD

**Issue by JrmCkh** [appoly/ARCore-Location#13]
Hi! The placed object in the specific location seems to glitch around and does not place towards the correct location. Is there anyway in solving this?

**Comment by johnwedgbury** [comment]
Hi @JrmCkh , 
Are you using the latest version of the library?

If yes, you can improve accuracy by ensuring your compass is calibrated.

Glitching can be caused by lack of trackable visual objects in ARCore, perhaps you're in a poorly lit area or moving the device erratically?

If the location marker is within about 100m, it may be that your detected device location isn't accurate enough to get a good bearing.

**Comment by johnwedgbury** [comment]
The markers are re-calculated every few seconds, and will move a little bit as the calculated direction of north changes.

If this behaviour doesn't suit what you are trying to do, you can change the interval to something greater (such as a minute) with:
locationScene.setAnchorRefreshInterval(60);
