### ISSUE TITLE
Rendering of markers not stable

### ISSUE THREAD

**Issue by mrCardizzle** [appoly/ARCore-Location#26]
Created an app using the library to display 5 location markers. Everything works fine, but the position of the rendered objects are not consistent. I assumed this was due to the compass error margin, but it somtimes shifts up to 180 degrees. Also noticed that the compass on the phone "spikes" by 50 degrees sometime independent of the shift of the objects. Am i the only one excperiencing that the objectes posistions are not consistent?

**Comment by johnwedgbury** [comment]
Have you tried increasing the refresh interval?
`locationScene.setAnchorRefreshInterval(60);`
Alternatively you can tell it to refresh only when it detects a location change from the device:
`locationScene.setRefreshAnchorsAsLocationChanges(true);`

You can also tell the library to stop trying to refine the angles so often with:
`locationScene.setMinimalRefreshing(true);`

Unfortunately due to the wide range of applications for the library, it's difficult to get the right behaviour for everyone by default! Let me know if none of the above helps.

**Comment by mrCardizzle** [comment]
Have tried all these things without success:
- Increasing the refresh interval led to the elements respawning all over the place.
- Refreshing on location change causes the app to spawn objects tilted before crashing the app.
- Enabling minimalrefreshing was no difference.

I am noticing that the objects are moving more vigorously when the phone is moved around faster. Could this be due to the objects rendered being dependent of the phones gyro? maybe ARcore trying to spawn objects only on recognized surfaces? This problem persist on the example code aswell as my own.
Thank you for answering.
