### ISSUE TITLE
Object Overlapping with the nearby lat long

### ISSUE THREAD

**Issue by harshadladva** [appoly/ARCore-Location#67]
I am facing problem in object overlapping. I am going to develop one AR application with GPS location and plot the objects of the nearby places.But When the lat long is about same it is overlapping with other object. I want to create distance between two objects. Please give me any suggestions.. Thank you in advance.

**Comment by harshadladva** [comment]
And i am doing navigation using real time object Map navigation. Is there any solution to navigate and show object to get the direction using object??Please give me any suggestion..Thank you..

**Comment by SheikhZayed** [comment]
did you try with `setOffsetOverlaping()` method from the library.

or you can also add the library as a local module to the app and modify the code as required for your needs.

while placing the anchor,the library makes use of some heightfactor to decide the cords for the anchor.

you can play around it by changing / modifying the code (i suggest you to use azimuth based approach rather than pitch) which will give you good results

**Comment by harshadladva** [comment]
Yes, I have added but it is not  fixed. object moves everytime. So how should i achieve it??And yes i have already added setRefreshInterval(99999) it don't show any object. Please Give me suggestion.

**Comment by harshadladva** [comment]
Ok Now i am going to use only setOffsetOverlapping for object overlapping problem it's works fine.

**Comment by yudikarma** [comment]
@SheikhZayed @harshadladva  are this issue mean ask for show AR only where user in narby at parameter location set  ? cause in my app, i want to display AR only when user is < 30 M from location setting to display AR object. exactly like Pokemen Go app. thats show Pokemon only in some location setting . sorry my bad english
